### ISSUE TITLE
建议优先考虑蓝牙

### ISSUE THREAD

**Issue by PaiGack** [yanxiangrong/LoveUmbrellaESP-RTOS#4]
蓝牙比WiFi靠谱
1、耗电低
2、成本低
3、无需额外联网

**Comment by yanxiangrong** [comment]
我们正在开发第二代伞架
![IMG_20220404_223514](https://user-images.githubusercontent.com/39958055/161568285-0a0748e2-4b9d-4f5f-8b43-7aa8623f9fdf.jpg)
第二代伞架仍然使用WIFI联网。

蓝牙方案相比我们的目前方案并不具有成本优势。
另外蓝牙具有局限性。
如果没有用户和伞架连接，那么我们就无法获得伞架的状态。

另外我们调查发现目前WIFI不稳定主要原因为WIFI信号质量不佳，更换一个WIFI接入点即可解决。
